### ISSUE TITLE
BUG Same post keeps getting re-counted

### ISSUE THREAD

**Issue by CodeBunTes** [H5YR/h5yr_u10#57]
More putting this in here as a reference place, but I'm currently trying to track down a bug that only seems to be affecting the live site around the total post counter. While the posts from Rick and Owain were correctly counted once yesterday as expected, my post made last night has kept getting re-counted every 15 minutes since so the post counter is going up way beyond what it should be (should only be up to 129).

This doesn't happen with the same code on the dev version which still shows the correct count. My current suspicion is that it's probably something related to timezones on the server being different to that of my dev machine, given we've only very recently changed to BST in the UK, but it's not yet proven.

**Comment by CodeBunTes** [comment]
@OwainWilliams On the live server, do you have the ability to see and screenshot what's currently held in the new PostCounter table? I'm going to try and compare this with my local version to see if I can isolate any difference better.

**Comment by OwainWilliams** [comment]
I'll see if @AaronSadlerUK can help with this one :D Aaron, is there a way I can see this or maybe even add @CodeBunTes to the admin area so he can have a look?

**Comment by AaronSadlerUK** [comment]
@OwainWilliams Sure, if you share the SQL connection string with @CodeBunTes he can connect via SQL Management Studio

https://my.umbhost.net/knowledgebase/11/How-do-I-manage-my-Microsoft-SQL-database.html

**Comment by CodeBunTes** [comment]
I believe I've managed to replicate the issue by swapping out SQLite for a fresh copy of SQL Express locally anyway, and looks like it may be down to a difference in how NPoco maps dates to the different underlying database types. Fix to follow shortly.
